import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { SmartReportType } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import { PrismaService } from '../../prisma/prisma.service';
import { DashboardService } from '../dashboard/dashboard.service';
import { FinanceService } from '../finance/finance.service';
import {
  buildPdf,
  renderExecutive,
  renderFinance,
  renderHr,
  renderProjects,
  reportsDir,
  type PdfDoc,
} from './pdf-builder';

const REPORT_META: Record<
  SmartReportType,
  { title: string; permission: string }
> = {
  EXECUTIVE: { title: 'Executive Dashboard Report', permission: 'dashboard.read' },
  FINANCE: { title: 'Finance Summary Report', permission: 'finance.read' },
  PROJECTS: { title: 'Projects Status Report', permission: 'projects.read' },
  HR: { title: 'HR & Performance Report', permission: 'hr.read' },
};

@Injectable()
export class ReportsService {
  constructor(
    private prisma: PrismaService,
    private dashboardService: DashboardService,
    private financeService: FinanceService,
  ) {}

  private can(permissions: string[], slug: string) {
    return permissions.includes('*') || permissions.includes(slug);
  }

  private assertTypeAccess(permissions: string[], type: SmartReportType) {
    const meta = REPORT_META[type];
    if (!this.can(permissions, meta.permission)) {
      throw new ForbiddenException(`No permission to generate ${type} reports`);
    }
  }

  listTypes(permissions: string[]) {
    return (Object.keys(REPORT_META) as SmartReportType[])
      .filter((type) => this.can(permissions, REPORT_META[type].permission))
      .map((type) => ({
        type,
        title: REPORT_META[type].title,
        description: TYPE_DESCRIPTIONS[type],
      }));
  }

  listHistory(userId: string, permissions: string[], limit = 30) {
    const allowedTypes = (Object.keys(REPORT_META) as SmartReportType[]).filter((t) =>
      this.can(permissions, REPORT_META[t].permission),
    );

    return this.prisma.smartReport.findMany({
      where: {
        OR: [{ generatedById: userId }, { type: { in: allowedTypes } }],
      },
      orderBy: { createdAt: 'desc' },
      take: limit,
      include: {
        generatedBy: { select: { firstName: true, lastName: true } },
      },
    });
  }

  async generate(type: SmartReportType, userId: string, permissions: string[]) {
    this.assertTypeAccess(permissions, type);

    const payload = await this.collectData(type, permissions);
    const meta = REPORT_META[type];
    const stamp = new Date().toISOString().slice(0, 10);
    const fileName = `${type.toLowerCase()}-${stamp}-${Date.now()}.pdf`;
    const filePath = path.join(reportsDir(), fileName);

    const subtitle = `Period: ${stamp} · Auto-generated by VegaCore OS`;

    const renderers: Record<SmartReportType, (doc: PdfDoc) => void> = {
      EXECUTIVE: (doc) => renderExecutive(doc, payload),
      FINANCE: (doc) => renderFinance(doc, payload),
      PROJECTS: (doc) => renderProjects(doc, payload),
      HR: (doc) => renderHr(doc, payload),
    };

    const fileSize = await buildPdf(filePath, meta.title, subtitle, renderers[type]);

    return this.prisma.smartReport.create({
      data: {
        type,
        title: `${meta.title} — ${stamp}`,
        fileName,
        filePath,
        fileSize,
        generatedById: userId,
      },
      include: {
        generatedBy: { select: { firstName: true, lastName: true } },
      },
    });
  }

  async getDownload(id: string, userId: string, permissions: string[]) {
    const report = await this.prisma.smartReport.findUnique({
      where: { id },
      include: { generatedBy: { select: { firstName: true, lastName: true } } },
    });
    if (!report) throw new NotFoundException('Report not found');

    this.assertTypeAccess(permissions, report.type);

    if (!fs.existsSync(report.filePath)) {
      throw new NotFoundException('PDF file missing on server');
    }

    return report;
  }

  private async collectData(
    type: SmartReportType,
    permissions: string[],
  ): Promise<Record<string, unknown>> {
    switch (type) {
      case 'EXECUTIVE': {
        const data = await this.dashboardService.getExecutiveDashboard(permissions);
        return data as unknown as Record<string, unknown>;
      }
      case 'FINANCE': {
        const dash = await this.financeService.getDashboard();
        return dash as unknown as Record<string, unknown>;
      }
      case 'PROJECTS': {
        const data = await this.dashboardService.getExecutiveDashboard(permissions);
        return { projects: data.projects };
      }
      case 'HR': {
        const exec = await this.dashboardService.getExecutiveDashboard(permissions);
        const perf = await this.prisma.performanceReport.findMany({
          orderBy: { createdAt: 'desc' },
          take: 20,
          include: {
            employee: { include: { user: { select: { firstName: true, lastName: true } } } },
          },
        });
        return {
          employees: exec.busyEmployees,
          performanceReports: perf.map((r) => ({
            employee: `${r.employee.user.firstName} ${r.employee.user.lastName}`,
            period: r.period,
            score: r.score,
          })),
        };
      }
      default:
        return {};
    }
  }
}

const TYPE_DESCRIPTIONS: Record<SmartReportType, string> = {
  EXECUTIVE: 'Projects, revenue, delays, and KPIs',
  FINANCE: 'Revenue, expenses, invoices, and profit',
  PROJECTS: 'Full portfolio status and deadlines',
  HR: 'Workload and performance scores',
};
